// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJYriQ12l0WWpofi6itqA459s_dqQUz1M',
    appId: '1:83845209931:web:bc7cd8cd688d8cff7b52ce',
    messagingSenderId: '83845209931',
    projectId: 'pulpoapp-d0c57',
    authDomain: 'pulpoapp-d0c57.firebaseapp.com',
    storageBucket: 'pulpoapp-d0c57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtW8lgQv-743a7QKNBAmFKlOTwkEF7rtg',
    appId: '1:83845209931:android:fe040dfd46518f367b52ce',
    messagingSenderId: '83845209931',
    projectId: 'pulpoapp-d0c57',
    storageBucket: 'pulpoapp-d0c57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA1X7FqSZEF34p6JAkWsrNs2FwpnOOP_g',
    appId: '1:83845209931:ios:fdd60fa0db4e6b2b7b52ce',
    messagingSenderId: '83845209931',
    projectId: 'pulpoapp-d0c57',
    storageBucket: 'pulpoapp-d0c57.firebasestorage.app',
    iosBundleId: 'com.example.flutterPulpoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA1X7FqSZEF34p6JAkWsrNs2FwpnOOP_g',
    appId: '1:83845209931:ios:fdd60fa0db4e6b2b7b52ce',
    messagingSenderId: '83845209931',
    projectId: 'pulpoapp-d0c57',
    storageBucket: 'pulpoapp-d0c57.firebasestorage.app',
    iosBundleId: 'com.example.flutterPulpoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJYriQ12l0WWpofi6itqA459s_dqQUz1M',
    appId: '1:83845209931:web:4d6e6ba312a217617b52ce',
    messagingSenderId: '83845209931',
    projectId: 'pulpoapp-d0c57',
    authDomain: 'pulpoapp-d0c57.firebaseapp.com',
    storageBucket: 'pulpoapp-d0c57.firebasestorage.app',
  );
}
