name: flutter_pulpoapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_ui_auth: ^1.16.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  lucide_icons: ^0.257.0
  lucide_icons_flutter: ^1.2.9
  mobile_scanner: ^6.0.7
  permission_handler: ^11.4.0
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.6.2
  
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
